module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#00419e',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#141d23',
        secondary: '#575f67',
        'on-tertiary-fixed-variant': '#004e5e',
        'secondary-fixed': '#dbe4ed',
        'on-tertiary-container': '#ffffff',
        'tertiary-fixed-dim': '#5fd5f5',
        'surface-bright': '#f7f9ff',
        error: '#ba1a1a',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#001f27',
        'secondary-fixed-dim': '#bfc8d0',
        'on-primary-container': '#ffffff',
        'on-error': '#ffffff',
        'surface-container-high': '#e5e8ee',
        'inverse-surface': '#2d3135',
        'on-surface': '#181c20',
        surface: '#f7f9ff',
        'secondary-container': '#d8e1ea',
        'inverse-primary': '#b1c5ff',
        'surface-variant': '#e0e3e8',
        'outline-variant': '#c2c6d8',
        primary: '#0057cd',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e0e3e8',
        'surface-tint': '#0057ce',
        'surface-dim': '#d7dadf',
        outline: '#727787',
        'primary-container': '#0d6efd',
        'primary-fixed': '#dae2ff',
        'surface-container-low': '#f1f4f9',
        'on-secondary-fixed-variant': '#3f484f',
        'on-secondary-container': '#5b646b',
        'on-secondary': '#ffffff',
        'surface-container': '#ebeef3',
        'tertiary-container': '#00829b',
        'primary-fixed-dim': '#b1c5ff',
        'on-background': '#181c20',
        tertiary: '#00677b',
        'on-surface-variant': '#424655',
        'inverse-on-surface': '#eef1f6',
        background: '#f7f9ff',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#001946',
        'tertiary-fixed': '#b0ecff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        base: '4px',
        'panel-width-expanded': '280px',
        gutter: '16px',
        'margin-desktop': '24px',
        'panel-width-collapsed': '48px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'headline-sm': ['Inter'],
        'label-sm': ['JetBrains Mono'],
        'label-md': ['JetBrains Mono'],
        'headline-md': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'display-lg': ['Inter'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
};
